name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install backend dependencies (si backend existe)
        run: |
          if [ -f backend/requirements.txt ]; then
            pip install -r backend/requirements.txt
          fi

      - name: Install ML dependencies (si ML existe)
        run: |
          if [ -f ml/requirements.txt ]; then
            pip install -r ml/requirements.txt
          fi

      - name: Run backend tests (si dossiers backend/tests existe)
        run: |
          if [ -d backend/tests ]; then
            pytest backend/tests/
          else
            echo "Pas de tests backend pour l'instant"
          fi

      - name: Run ML tests (si dossiers ml/tests existe)
        run: |
          if [ -d ml/tests ]; then
            pytest ml/tests/
          else
            echo "Pas de tests ML pour l'instant"
          fi

      - name: Build frontend (si frontend existe)
        run: |
          if [ -d frontend ]; then
            cd frontend
            npm install
            npm run build
          else
            echo "Pas de frontend pour l'instant"
          fi
